#ifndef WIFI_CONN_H
#define WIFI_CONN_H

#define ESP_CAM_WIFI_SSID      CONFIG_ESP_WIFI_SSID
#define ESP_CAM_WIFI_PASS      CONFIG_ESP_WIFI_PASSWORD
#define ESP_CAM_MAXIMUM_RETRY  CONFIG_ESP_MAXIMUM_RETRY

void wifi_init_sta(void);

#endif